WebApplicationMVC/Models/ContattoModel.cs
namespace WebApplicationMVC.Models
{
    public class ContattoModel
    {
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public int Eta { get; set; }
       
        public int Sesso {  get; set; }

        public List<Sesso> Generi { get; set; }

    }

    public class Sesso
    {
        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

WebApplicationMVC/Models/ErrorViewModel.cs
namespace WebApplicationMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationMVC/Models/ListModel.cs
namespace WebApplicationMVC.Models
{
    public class ListModel
    {
        public List<ContattoModel> Contatti { get; set;}
        public List<Sesso> Generi { get; set; } 
    }
}

WebApplicationMVC/Controllers/AnagraficaController.cs
using Microsoft.AspNetCore.Mvc;
using Model;
using Model.Anagrafica;
using Service;


namespace WebApplicationMVC.Controllers
{
    public class AnagraficaController : Controller
    {

        private AnagraficaService _anagraficaService;

        public AnagraficaController(AnagraficaService anagraficaService )
        {
            _anagraficaService = anagraficaService;
        }

        [HttpGet]
        public IActionResult CreateUpdate()
        {
            AnagraficaInputModel model = new AnagraficaInputModel();

            model.Generi = _anagraficaService.GetGeneri();

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> CreateUpdate(AnagraficaInputModel input)
        {
            BaseOutput output = await _anagraficaService.Create(input);

            if(!output.Success)
            {
                //Fallimento
                input.Output = output;
                input.Generi = _anagraficaService.GetGeneri();

                return View(input);
            }
            else
            {
                //Successo
                return RedirectToAction("Lista");
            }
        }



        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            ListaAnagraficheModel model = new ListaAnagraficheModel();

            model = await _anagraficaService.GetListAnagrafiche();
          
            return View(model);
        }


    }
}

WebApplicationMVC/Controllers/DiarioController.cs
using Microsoft.AspNetCore.Mvc;
using Model.Diario;
using Service;

namespace WebApplicationMVC.Controllers
{
    public class DiarioController :  Controller
    {
        private DiarioService diarioService;

        public DiarioController(DiarioService diarioS) 
        { 
            diarioService = diarioS;
        }

        [HttpGet]
        public IActionResult Diario(int idAnagrafica) 
        { 
            DiarioAlimentareModel model = new DiarioAlimentareModel();

            model = diarioService.GetAlimentareModel(idAnagrafica);

            return View("DiarioAlimentare", model);
        }


        public IActionResult Check(int idAnagrafica)
        {
            return View();

        }


    }
}

WebApplicationMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplicationMVC.Models;

namespace WebApplicationMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Contatto()
        {
            ContattoModel model = new ContattoModel()
            {
                Nome = "Julienne",
                Cognome = "Mirabella",
                Eta = 22
            };
            
            return View(model);
        }

   
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationMVC/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationMVC.Models;

namespace WebApplicationMVC.Controllers
{
    public class RegisterController : Controller
    {
        private List<Sesso> generi  = new List<Sesso>() {
                    new Sesso() { Id = 1, Nome = "F" },
                    new Sesso() { Id = 2, Nome = "M" },
                    new Sesso() { Id = 3, Nome = "N" },
                };

        [HttpGet]

        public IActionResult Registrazione()
        {
            ContattoModel model = new ContattoModel()
            {
                Generi = generi
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Registrazione(ContattoModel modelInput)
        {
            ListModel listModel = new ListModel()
            {
                Contatti = new List<ContattoModel>()
                {
                    modelInput
                },
                Generi = generi
            };

            
            return View("Lista", listModel);
            
        }






    }
}

WebApplicationMVC/Views/Anagrafica/CreateUpdate.cshtml
@model Model.Anagrafica.AnagraficaInputModel

<h1>Registrazione nuovo cliente</h1>

@if(!Model.Output.Success)
{
    <div class="alert alert-danger" role="alert">
       @Model.Output.ErrorMessage
    </div>
}

<form asp-action="CreateUpdate" asp-controller="Anagrafica" method="post">

    <label class="form-label">Nome:</label>
    <input asp-for="Nome" class="form-control" />

    <label class="form-label">Cognome:</label>
    <input asp-for="Cognome" class="form-control" />

    <label class="form-label">Età:</label>
    <input asp-for="Eta" class="form-control" />

    <label class="form-label">Peso attuale:</label>
    <input asp-for="PesoAttuale" class="form-control" />

    <label class="form-label">Altezza:</label>
    <input asp-for="Altezza" class="form-control" />

    <label class="form-label">Genere:</label>
    @Html.DropDownListFor(model => model.IdGenere, Model.Generi.Select(x => new SelectListItem() { Text = x.Genere, Value = x.Id.ToString() }),
            "-- seleziona --", htmlAttributes: new { @class = "form-control" })


    <label class="form-label">Consenso alla privacy:</label>
    <input type="checkbox" asp-for="ConsensoPrivacy" class="form-check-input" />

    <br />
    <label class="form-label">Note:</label>
    <textarea asp-for="Note" class="form-control" ></textarea>


    <br />
    <button type="submit" class="btn-success">Registra</button>
</form>

WebApplicationMVC/Views/Anagrafica/Lista.cshtml
@model Model.Anagrafica.ListaAnagraficheModel

<h1>Lista delle anagrafiche</h1>

<table class="table table-striped">
    <tr>
        <th>
            Cognome
        </th>
        <th>
            Nome
        </th>
        <th>
            Età
        </th>
        <th>
            Genere
        </th>
        <th>

        </th>
    </tr>
    @foreach (var anagrafica in Model.Anagrafiche)
    {
        <tr>
            <td>
                @anagrafica.Cognome
            </td>
            <td>
                @anagrafica.Nome
            </td>
            <td>
                @anagrafica.Eta
            </td>
            <td>
                @anagrafica.Genere
            </td> 
            <td>
                <a asp-action="Diario" asp-controller="Diario" asp-route-idAnagrafica="@anagrafica.IdAnagrafica">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-balloon-heart" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="m8 2.42-.717-.737c-1.13-1.161-3.243-.777-4.01.72-.35.685-.451 1.707.236 3.062C4.16 6.753 5.52 8.32 8 10.042c2.479-1.723 3.839-3.29 4.491-4.577.687-1.355.587-2.377.236-3.061-.767-1.498-2.88-1.882-4.01-.721zm-.49 8.5c-10.78-7.44-3-13.155.359-10.063q.068.062.132.129.065-.067.132-.129c3.36-3.092 11.137 2.624.357 10.063l.235.468a.25.25 0 1 1-.448.224l-.008-.017c.008.11.02.202.037.29.054.27.161.488.419 1.003.288.578.235 1.15.076 1.629-.157.469-.422.867-.588 1.115l-.004.007a.25.25 0 1 1-.416-.278c.168-.252.4-.6.533-1.003.133-.396.163-.824-.049-1.246l-.013-.028c-.24-.48-.38-.758-.448-1.102a3 3 0 0 1-.052-.45l-.04.08a.25.25 0 1 1-.447-.224l.235-.468ZM6.013 2.06c-.649-.18-1.483.083-1.85.798-.131.258-.245.689-.08 1.335.063.244.414.198.487-.043.21-.697.627-1.447 1.359-1.692.217-.073.304-.337.084-.398" />
                    </svg>
                </a>
            </td>
        </tr>
    }
</table>

WebApplicationMVC/Views/Diario/DiarioAlimentare.cshtml
@model Model.Diario.DiarioAlimentareModel

<h1>Diario Alimentare di @Model.Anagrafica.Nome @Model.Anagrafica.Cognome</h1>


<div class="row">
    <div class="col-md-4">
        <h2>@Model.Anagrafica.Nome @Model.Anagrafica.Cognome</h2>
        <br />
        <p>
            <b>Età: </b> @Model.Anagrafica.Eta 
        </p>
        <br />
        <p>
            <b>Peso iniziale: </b>@Model.PesoIniziale
        </p>
        <br />
        <p>
            <b>Altezza iniziale: </b>@Model.AltezzaIniziale
        </p>
    </div>

    <div class="col-md-6">
        <table class="table table-striped">
            <tr>
                <th>
                    Data Registrazione
                </th>
                <th>
                    Peso
                </th>
                <th>
                    Altezza
                </th>
                <th>
                    %
                </th>
            </tr>
            @foreach (var check in Model.Diario)
            {
               <tr>
                   <td>
                       @check.DataRegistrazione
                   </td>
                   <td>
                       @check.Peso
                   </td>
                   <td>
                       @check.Altezza
                   </td>
                   <td>

                   </td>
               </tr>
            }


        </table>
    </div>
    <div class="col-md-2">
        <a class="btn btn-dark">
            +
        </a>
    </div>
</div>

WebApplicationMVC/Views/Home/Contatto.cshtml
@model WebApplicationMVC.Models.ContattoModel

<h1>Pagina di contatto</h1>

<div class="row">
    <div class="col-md-6">
        <p>
            @Model.Nome  @Model.Cognome
        </p>

    </div>
    <div class="col-md-6">
        <p>
            @Model.Eta 
        </p>

    </div>
</div>

WebApplicationMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplicationMVC/Views/Register/Lista.cshtml
@model WebApplicationMVC.Models.ListModel

<table class="table-bordered">
    <tr>
        <th>
            Nome
        </th>
        <th>
            Cognome
        </th>
        <th>
            Età
        </th>
        <th>
            Sex
        </th>
    </tr>
   
    @foreach(var contatto in Model.Contatti)
    { 
        <tr> 
          <td>
              @contatto.Nome
          </td>
          <td>
              @contatto.Cognome
          </td>
          <td>
              @contatto.Eta
          </td>
          <td>
              @Model.Generi.First(x => x.Id == contatto.Sesso).Nome
          </td>
        </tr>
      }
    
</table>

WebApplicationMVC/Views/Register/Registrazione.cshtml
@model WebApplicationMVC.Models.ContattoModel

<div class="col-md-9 offset-2">
    <form asp-action="Registrazione" asp-controller="Register" method="post">
        <label class="form-label">
            Nome:
        </label>
        <input asp-for="Nome" class="form-control"/>
        <label class="form-label">
            Cognome:
        </label>
        <input asp-for="Cognome" class="form-control"/>
        <label class="form-label">
            Età:
        </label>
        <input asp-for="Eta" class="form-control" />
        @Html.DropDownListFor(model => model.Sesso, 
            Model.Generi.Select(x => new SelectListItem() { Text = x.Nome, Value = x.Id.ToString() }), 
            "-- seleziona --", htmlAttributes: new { @class = "form-control", @id="dropSex" })
       
        <br />
        <button type="submit" class="btn-danger" >Registrati</button>
    </form>
</div>

WebApplicationMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationMVC.styles.css" asp-append-version="true" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Anagrafica" asp-action="CreateUpdate">Nuovo Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Anagrafica" asp-action="Lista">Clienti</a>
                        </li>

                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Contatto">Contatto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Register" asp-action="Registrazione">Registrati</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebApplicationMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>